[env]
PKG_CONFIG_PATH = { value = "third_party/ffmpeg/lib/pkgconfig", relative = true, force = false }
FFMPEG_INCLUDE_DIR = { value = "third_party/ffmpeg/include", relative = true }
FFMPEG_LIB_DIR = { value = "third_party/ffmpeg/lib", relative = true }